"""Corpus synthétiques des contrôles S3 (copie contractuelle des sujets)."""

C1 = {'texte_musee': "Les médiatrices accueillent les visiteurs. Une visiteuse observe une maquette, puis les enfants dessinent. L'atelier ferme à midi !", 'texte_transport': "Le tram arrive. Les voyageuses montent ; un agent annonce l'arrêt. Attention !", 'texte_meteo': 'La pluie revient. Les riverains ferment les fenêtres.'}

C2 = {'texte_atelier': "Les bénévoles réparent des vélos. Une bénévole nettoie les roues et répare une lampe. Les clients apportent des objets fragiles. L'atelier conserve les pièces utiles ; les bénévoles expliquent les réparations. Chaque semaine, des cyclistes confient leurs vélos aux bénévoles. Les roues usées rejoignent une table de contrôle. Un technicien examine les freins et remplace les pièces abîmées. Deux bénévoles nettoient une lampe ancienne, puis testent ses composants. Les clients observent les réparations et posent des questions. Dans cet atelier, les vélos occupent une place importante, mais les lampes attirent aussi des visiteurs. Une cliente apporte des roues supplémentaires pour réparer un vélo. Les bénévoles notent les pièces réutilisées et expliquent les limites de chaque réparation.", 'texte_alimentation': 'Les cuisinières préparent des soupes. Un cuisinier découpe les légumes et conserve les restes. Les clientes choisissent des produits locaux. La cuisine partage ses recettes. Chaque matin, les cuisinières lavent les légumes et préparent une soupe différente. Les clientes demandent la liste des ingrédients et comparent les recettes. Une cuisinière conserve les fanes pour une nouvelle préparation. Les produits locaux arrivent dans des caisses réutilisables. Un cuisinier explique comment transformer les restes en soupe. La cuisine accueille des familles qui apportent leurs légumes. Les recettes circulent entre les familles et les cuisinières. Les clientes apprécient les soupes, mais interrogent aussi les conditions de conservation des produits.', 'annotations_port': [{'forme': 'Les', 'lemme': 'le', 'pos': 'DET', 'mot_vide': True}, {'forme': 'marins', 'lemme': 'marin', 'pos': 'NOUN', 'mot_vide': False}, {'forme': 'chargent', 'lemme': 'charger', 'pos': 'VERB', 'mot_vide': False}, {'forme': 'les', 'lemme': 'le', 'pos': 'DET', 'mot_vide': True}, {'forme': 'caisses', 'lemme': 'caisse', 'pos': 'NOUN', 'mot_vide': False}, {'forme': '.', 'lemme': '.', 'pos': 'PUNCT', 'mot_vide': False}, {'forme': 'Une', 'lemme': 'un', 'pos': 'DET', 'mot_vide': True}, {'forme': 'caisse', 'lemme': 'caisse', 'pos': 'NOUN', 'mot_vide': False}, {'forme': 'reste', 'lemme': 'rester', 'pos': 'VERB', 'mot_vide': False}, {'forme': 'ouverte', 'lemme': 'ouvert', 'pos': 'ADJ', 'mot_vide': False}, {'forme': '.', 'lemme': '.', 'pos': 'PUNCT', 'mot_vide': False}], 'expression': 'produits locaux'}

C3 = {'texte_patrimoine': 'Le conseil conserve les plans. Les plans anciens restent consultables. Une responsable déclare : « L’atelier ouvre lundi. »\nLe chantier transforme une cour en jardin. Un plan signale la cour ; les plans ne décrivent pas tous les usages. Le conseil publie les comptes rendus.', 'citations': [{'id': 'P1', 'citation': 'Les plans anciens restent consultables.'}, {'id': 'P2', 'citation': "l'atelier   ouvre lundi."}, {'id': 'P3', 'citation': 'Le chantier transforme une cour en parking.'}, {'id': 'P4', 'citation': 'Le conseil refuse les archives.'}], 'texte_radio': 'Le port ouvre jeudi. Une porte reste fermée. Le bulletin répète : le port ouvre jeudi. Les ports voisins restent ouverts.', 'citations_radio': [{'id': 'R1', 'citation': 'Le port ouvre jeudi.'}, {'id': 'R2', 'citation': 'le port ouvre vendredi.'}], 'tests_concordance': [{'id': 'T1', 'source': 'plan plan', 'motif': 'plan', 'largeur': 3}, {'id': 'T2', 'source': 'plantation plan', 'motif': 'plan', 'largeur': 4}, {'id': 'T3', 'source': '', 'motif': 'plan', 'largeur': 2}, {'id': 'T4', 'source': 'plan', 'motif': '', 'largeur': 2}]}

C4 = {'mobilite': [['bus', 'retard', 'bus'],
              ['tram', 'accès'],
              ['bus', 'accès', 'retard'],
              ['bus', 'travaux'],
              ['retard', 'travaux'],
              ['bus', 'accès'],
              ['vélo', 'accès'],
              ['tram', 'retard']],
 'flux_mobilite': ['bus', 'arrive', '.', 'retard', 'puis', 'bus', 'accès', '.', 'retard'],
 'dossiers_mobilite': [[0, 1], [2, 3], [4, 5], [6, 7]],
 'annotations_mobilite': [{'forme': 'retards', 'lemme': 'retard'},
                          {'forme': 'retard', 'lemme': 'retard'},
                          {'forme': 'retarder', 'lemme': 'retarder'},
                          {'forme': 'retardataire', 'lemme': 'retardataire'}],
 'acces_mobilite': [['accès', 'libre'],
                    ['accès', 'vraiment', 'libre'],
                    ['accès', 'libre', 'accès', 'libre'],
                    ['libre', 'accès']],
 'texte_mobilite': 'Les retards peuvent retarder le bus. Un retardataire demande un accès libre.',
 'archives_sonores': [['voix', 'bruit', 'voix'],
                      ['mémoire', 'orale', 'voix'],
                      ['bruit', 'silence'],
                      ['voix', 'silence', 'bruit'],
                      ['mémoire', 'vive', 'orale'],
                      ['voix', 'silence'],
                      ['bruit'],
                      ['mémoire', 'orale', 'bruit']],
 'texte_archives': 'Une voix traverse le bruit. La mémoire orale conserve des voix. Le silence ne prouve pas '
                   'une absence de témoignage.'}

C5 = {'mediation': [['visite', 'audio'],
               ['visite', 'audio', 'atelier'],
               ['visite', 'audio'],
               ['visite', 'atelier'],
               ['audio', 'plan'],
               ['audio', 'plan'],
               ['audio'],
               ['plan'],
               ['guide', 'plan'],
               ['audio']],
 'sections_musee': {'court': ['visite',
                              'audio',
                              'visite',
                              'plan',
                              'visite',
                              'guide',
                              'salle',
                              'audio',
                              'plan',
                              'fin'],
                    'long': ['visite',
                             'audio',
                             'plan',
                             'salle',
                             'guide',
                             'visite',
                             'public',
                             'audio',
                             'plan',
                             'salle',
                             'visite',
                             'guide',
                             'audio',
                             'public',
                             'salle',
                             'visite',
                             'plan',
                             'audio',
                             'guide',
                             'public',
                             'visite',
                             'salle',
                             'audio',
                             'plan',
                             'fin']},
 'flux_musee': ['visite',
                'audio',
                'et',
                'plan',
                'visite',
                'sans',
                'audio',
                '.',
                'visite',
                'seule',
                '.',
                'audio'],
 'bulletins_littoral': [['plage', 'vent'],
                        ['plage', 'alerte'],
                        ['plage'],
                        ['plage', 'vent', 'alerte'],
                        ['vent', 'alerte'],
                        ['vent'],
                        ['port'],
                        ['vent']],
 'texte_musee': 'La visite utilise un guide audio. Un atelier permet aussi une visite sans guide audio. Le '
                'plan du musée ne décrit pas toutes les pratiques.',
 'texte_littoral': 'Le vent atteint la plage. Une alerte ne concerne pas toutes les plages. Le port reste '
                   'ouvert malgré le vent.'}

C6 = {'texte_exposition': 'Une affiche annonce une exposition. Le public observe cette affiche. Un atelier '
                     'accueille le public. Une affiche présente un atelier. Le public quitte la salle. Cette '
                     'exposition propose un atelier. Le public discute une affiche. Un atelier termine cette '
                     'exposition.',
 'flux_exposition': ['Une',
                     'affiche',
                     'annonce',
                     'une',
                     'exposition',
                     '.',
                     'Le',
                     'public',
                     'observe',
                     'cette',
                     'affiche',
                     '.',
                     'Un',
                     'atelier',
                     'accueille',
                     'le',
                     'public',
                     '.',
                     'Une',
                     'affiche',
                     'présente',
                     'un',
                     'atelier',
                     '.',
                     'Le',
                     'public',
                     'quitte',
                     'la',
                     'salle',
                     '.',
                     'Cette',
                     'exposition',
                     'propose',
                     'un',
                     'atelier',
                     '.',
                     'Le',
                     'public',
                     'discute',
                     'une',
                     'affiche',
                     '.',
                     'Un',
                     'atelier',
                     'termine',
                     'cette',
                     'exposition',
                     '.'],
 'fiches_exposition': [['une', 'affiche', 'annonce', 'une', 'exposition', '.'],
                       ['le', 'public', 'observe', 'cette', 'affiche', '.'],
                       ['un', 'atelier', 'accueille', 'le', 'public', '.'],
                       ['une', 'affiche', 'présente', 'un', 'atelier', '.'],
                       ['le', 'public', 'quitte', 'la', 'salle', '.'],
                       ['cette', 'exposition', 'propose', 'un', 'atelier', '.'],
                       ['le', 'public', 'discute', 'une', 'affiche', '.'],
                       ['un', 'atelier', 'termine', 'cette', 'exposition', '.']],
 'termes_exposition': ['affiche', 'public', 'atelier'],
 'texte_ateliers': 'Un prototype ouvre notre atelier. Cet atelier compare deux prototypes. Le groupe décrit '
                   'son prototype. Un atelier transforme le projet. Le prototype reste fragile.',
 'flux_ateliers': ['Un',
                   'prototype',
                   'ouvre',
                   'notre',
                   'atelier',
                   '.',
                   'Cet',
                   'atelier',
                   'compare',
                   'deux',
                   'prototypes',
                   '.',
                   'Le',
                   'groupe',
                   'décrit',
                   'son',
                   'prototype',
                   '.',
                   'Un',
                   'atelier',
                   'transforme',
                   'le',
                   'projet',
                   '.',
                   'Le',
                   'prototype',
                   'reste',
                   'fragile',
                   '.'],
 'termes_ateliers': ['atelier', 'prototype']}

C7 = {'texte_mediatheque': 'Le livre accompagne un atelier public.\n'
                      'Un accès libre accueille le public avec un livre.\n'
                      'Le livre nourrit un atelier, puis un autre atelier.\n'
                      'Cet accès au public reste libre.\n'
                      'Le livre ouvre un débat public.\n'
                      'Un atelier rassemble le public.\n'
                      'Un accès libre précède un atelier public.\n'
                      'Le silence accompagne le livre.\n'
                      'Les livres demandent le silence.\n'
                      'La livraison arrive avant un atelier.',
 'phrases_mediatheque': [['le', 'livre', 'accompagne', 'un', 'atelier', 'public', '.'],
                         ['un', 'accès', 'libre', 'accueille', 'le', 'public', 'avec', 'un', 'livre', '.'],
                         ['le',
                          'livre',
                          'nourrit',
                          'un',
                          'atelier',
                          ',',
                          'puis',
                          'un',
                          'autre',
                          'atelier',
                          '.'],
                         ['cet', 'accès', 'au', 'public', 'reste', 'libre', '.'],
                         ['le', 'livre', 'ouvre', 'un', 'débat', 'public', '.'],
                         ['un', 'atelier', 'rassemble', 'le', 'public', '.'],
                         ['un', 'accès', 'libre', 'précède', 'un', 'atelier', 'public', '.'],
                         ['le', 'silence', 'accompagne', 'le', 'livre', '.'],
                         ['les', 'livres', 'demandent', 'le', 'silence', '.'],
                         ['la', 'livraison', 'arrive', 'avant', 'un', 'atelier', '.']],
 'affirmations_mediatheque': [{'id': 'M1',
                               'pivots': [['livre']],
                               'associes': [['atelier']],
                               'intervalle': [2, 3],
                               'unite': 'présence par phrase',
                               'fenetre': 'phrase entière',
                               'normalisation': 'formes minuscules',
                               'agregation': 'union'},
                              {'id': 'M2',
                               'pivots': [['accès', 'libre']],
                               'associes': [['public']],
                               'intervalle': [3, 4],
                               'unite': 'présence par phrase',
                               'fenetre': 'phrase entière',
                               'normalisation': 'formes minuscules',
                               'agregation': 'union'},
                              {'id': 'M3',
                               'pivots': [['livre']],
                               'associes': [['atelier'], ['public']],
                               'intervalle': [4, 5],
                               'unite': 'présence par phrase',
                               'fenetre': 'phrase entière',
                               'normalisation': 'formes minuscules',
                               'agregation': None},
                              {'id': 'M4',
                               'pivots': [['livre'], ['livres']],
                               'associes': [['silence']],
                               'intervalle': [0, 0],
                               'unite': 'présence par phrase',
                               'fenetre': 'phrase entière',
                               'normalisation': 'formes minuscules',
                               'agregation': 'union'}],
 'citations_mediatheque': [{'id': 'C1', 'texte': 'Le livre ouvre un débat public.'},
                           {'id': 'C2', 'texte': 'Le livre interdit un débat public.'},
                           {'id': 'C3', 'texte': 'un accès libre accueille le public avec un livre.'}],
 'texte_jardin': 'Le sol reçoit une eau de pluie.\n'
                 'Le compost protège le sol.\n'
                 'Une eau de pluie humidifie le compost et le sol.\n'
                 'Le sol sèche.\n'
                 'Une eau claire traverse le jardin.\n'
                 'Le compost mûrit.\n'
                 'Une eau reste loin de la pluie.',
 'phrases_jardin': [['le', 'sol', 'reçoit', 'une', 'eau', 'de', 'pluie', '.'],
                    ['le', 'compost', 'protège', 'le', 'sol', '.'],
                    ['une', 'eau', 'de', 'pluie', 'humidifie', 'le', 'compost', 'et', 'le', 'sol', '.'],
                    ['le', 'sol', 'sèche', '.'],
                    ['une', 'eau', 'claire', 'traverse', 'le', 'jardin', '.'],
                    ['le', 'compost', 'mûrit', '.'],
                    ['une', 'eau', 'reste', 'loin', 'de', 'la', 'pluie', '.']],
 'affirmations_jardin': [{'id': 'J1',
                          'pivots': [['eau']],
                          'associes': [['sol'], ['compost']],
                          'intervalle': [2, 2],
                          'unite': 'présence par phrase',
                          'fenetre': 'phrase entière',
                          'normalisation': 'formes minuscules',
                          'agregation': 'union'},
                         {'id': 'J2',
                          'pivots': [['eau', 'de', 'pluie']],
                          'associes': [['compost']],
                          'intervalle': [2, 3],
                          'unite': 'présence par phrase',
                          'fenetre': 'phrase entière',
                          'normalisation': 'formes minuscules',
                          'agregation': 'union'},
                         {'id': 'J3',
                          'pivots': [['eau']],
                          'associes': [['sol']],
                          'intervalle': [1, 3],
                          'unite': 'présence par phrase',
                          'fenetre': None,
                          'normalisation': 'formes minuscules',
                          'agregation': 'union'}],
 'citation_jardin': 'Le sol sèche.'}
